name: Build EDParot for Windows

on:
  push:
    tags:
      - "Release/*"
  workflow_dispatch:

jobs:
  test:
    name: Build EDParot
    runs-on: windows-2019

    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.0
        with:
          python-version: "3.9.9"
          architecture: "x86"

      - name: Install python tools
        run: |
          pip install wheel
          pip install -r requirements.txt
      - name: Build EDParot
        run: |
          pyinstaller --onefile edparrot.py
      - name: Upload build files
        uses: actions/upload-artifact@v2
        with:
          name: Built files
          path: D:\a\EDParrot\EDParrot\dist\edparrot.exe

  release:
    name: Release new version
    runs-on: ubuntu-latest
    needs: test
    if: "${{ github.event_name != 'workflow_dispatch' }}"

    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: Built files
          path: ./
          
      - name: Hash files
        run: sha256sum edparot.exe > ./hashes.sum

      - name: Create Draft Release
        uses: "softprops/action-gh-release@v1"
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          draft: true
          prerelease: true
          discussion_category_name: "Announcement"
          files: |
            ./edparot.exe
            ./hashes.sum
